name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix: # Версия node.js
        node-version: [ 17.x ] # Версия node.js наша

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }} # стартуем на node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} # Указываем нашу версию node.js
      - name: install modules
        run: npm install # run сервер, который запускает ваши рабочие процессы при их запуске # npm install запускаем сборку проета
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
#      - name: screenshot testing
#        run: npm run test:ui:ci